defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "default"
    permalink: /:basename
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
title: Vortex Gallery
tagline: "Bring Your Own Mix."
description: "Bring Your Own Mix. Online, global community tournaments coming to you starting October through November 2024."
twitch: https://twitch.tv/956productions
twitter: 
  username: 956productions
  card: summary
logo: /img/logo.png
youtube: https://956pro.com/youtube
nav:
  - title: FAQ
    url: /faq
  - title: Discord
    url: https://discord.gg/QDU8kEyDXM
  - title: Results
    url: https://956.productions/results
volunteer: /volunteer
collections:
  - extra