defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "default"
    permalink: /:basename
plugins:
  - jekyll-seo-tag
title: Vortex Gallery
tagline: "Vortex Gallery Online 2023"
description: "Bring Your Own Mix. February 10 - March 5, 2023."
twitch: https://twitch.tv/956productions
twitter: 
  username: 956productions
  card: summary
logo: /img/logo.png
youtube: https://956pro.com/youtube
nav:
  - title: FAQ
    url: /faq
  - title: Info
    url: /info
  - title: Schedule
    url: /schedule
  - title: Volumes
    url: /volumes
  - title: Discord
    url: https://discord.gg/wTWRM9uBBt
volunteer: /volunteer