defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "default"
    permalink: /:basename
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
title: Vortex Gallery
tagline: "The Community Tournaments at Frosty Faustings XVI"
description: "Vortex Gallery is the Community Tournaments at Frosty Faustings XVI. January 25-28, 2024 at The Westin in Lombard, IL."
twitch: https://twitch.tv/956productions
twitter: 
  username: 956productions
  card: summary
logo: /img/logo.png
youtube: https://956pro.com/youtube
nav:
  - title: Frosty Faustings XVI
    url: https://frostyfaustings.com
  - title: FAQ
    url: /faq
  - title: Discord
    url: https://discord.gg/wTWRM9uBBt
  - title: Results
    url: https://956.productions/results
volunteer: /volunteer